### ISSUE TITLE
Setting display folders

### ISSUE THREAD

**Issue by systemnova** [pbixr/pbixr#4]
Looking through the functions it looks like this package can edit the .pbix file, but the vignettes only cover reading.

Is there any chance you could extend it to include if it's possible to edit things like display folders with this package?

I've used DAX Studio & TabularEditor to achieve this in the past, but cant get these tools in my current workspace. I also don't have permissions to access terminal in my workspace, which blocks some of the Pibxr functions. 
It would be great to set from R the display folders, instead of having to manually do so for each new parquet export / project.

**Comment by pbixr** [comment]
Thanks for the feedback @systemnova . Unfortunately, I can't extend it to do edits. Check out this: https://dax.tips/2020/07/09/using-visual-studio-code-with-power-bi/
